DROP TABLE CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER (
  ID   VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO CUSTOMER
(ID, NAME) VALUES
  ('cc1', 'John');

DROP TABLE ACCOUNT;
CREATE TABLE IF NOT EXISTS ACCOUNT (
  CUSTOMER_ID VARCHAR(255) NOT NULL,
  NAME        VARCHAR(3)   NOT NULL,
  BALANCE     VARCHAR(255) NOT NULL,
  CURRENCY    VARCHAR(3)   NOT NULL,
  LAST_UPDATE TIMESTAMP    NOT NULL,
  PRIMARY KEY (CUSTOMER_ID, NAME)
);

INSERT INTO ACCOUNT (CUSTOMER_ID, NAME, BALANCE, CURRENCY, LAST_UPDATE) VALUES
  ('cc1', 'EUR', '14.15', 'EUR', '2017-12-31T10:49:34.873Z'),
  ('cc1', 'GBP', '1', 'GBP', '2017-12-13T09:40:34.873Z');
