DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
  ID   VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO CUSTOMER
(ID, NAME) VALUES
  ('cc1', 'John');

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
  CUSTOMER_ID VARCHAR(255) NOT NULL,
  NAME        VARCHAR(3)   NOT NULL,
  BALANCE     VARCHAR(255) NOT NULL,
  CURRENCY    VARCHAR(3)   NOT NULL,
  LAST_UPDATE TIMESTAMP    NOT NULL,
  PRIMARY KEY (CUSTOMER_ID, NAME)
);

INSERT INTO ACCOUNT (CUSTOMER_ID, NAME, BALANCE, CURRENCY, LAST_UPDATE) VALUES
  ('cc1', 'EUR', '14.15', 'EUR', '2017-12-31T10:49:34.873Z'),
  ('cc1', 'GBP', '1', 'GBP', '2017-12-13T09:40:34.873Z');


DROP TABLE IF EXISTS TRANSFER;
CREATE TABLE TRANSFER (
  ID            VARCHAR(255) AUTO_INCREMENT,
  CUSTOMER_ID   VARCHAR(255) NOT NULL,
  ACCOUNT_FROM  VARCHAR(3)   NOT NULL,
  ACCOUNT_TO    VARCHAR(3)   NOT NULL,
  AMOUNT        VARCHAR(255) NOT NULL,
  EXCHANGE_RATE VARCHAR(255) NOT NULL,
  NOTE          VARCHAR(255),
  CREATION_DATE TIMESTAMP    NOT NULL,
  PRIMARY KEY (ID)
);
